language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

install:

  # Create MySQL Database
  - mysql -e 'create database drupal;'

  # Install Drush
  - pear channel-discover pear.drush.org
  - pear install drush/drush-5.4.0
  - phpenv rehash

  # Run composer
  - cd ./tests/behat
  - composer install
  - cd ../../

before_script:

  # Install Classic Profile
  - cd ../
  - mkdir profiles
  - mv classic profiles/
  - mkdir drupal
  - mv profiles drupal/
  - cd drupal
  - drush make --prepare-install profiles/classic/build-classic.make --yes
  - sudo chmod -R 777 sites/all/modules
  - drush si classic --sites-subdir=default --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=classic --site-mail=admin@example.com --site-name="Drupal Classic Profile" --yes
  - drush cc all --yes
  - cd ../

  # Setup display for selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - sudo drush --root=$PWD/drupal runserver --server=builtin 80 &
  - sleep 3

  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.25.0.jar
  - java -jar selenium-server-standalone-2.25.0.jar -p 4444 &
  - sleep 5

script:
  - cd drupal/profiles/classic/tests/behat
  # behat.yml includes behat.local.yml so it must exist
  - touch behat.local.yml
  - ./bin/behat
